import * as stylex from '@stylexjs/stylex';

export const tokens = stylex.defineVars({
  '--font-sans': '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
  '--font-serif': 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
  '--font-mono': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  '--color-red': 'red',
  '--color-blue': 'yellow',
  '--spacing': '0.25rem',
  '--breakpoint-xs': '30rem',
  '--breakpoint-sm': '40rem',
  '--breakpoint-md': '48rem',
  '--breakpoint-lg': '64rem',
  '--breakpoint-xl': '80rem',
  '--breakpoint-2xl': '96rem',
  '--text-heading-4xl': '2.25rem',
  '--text-heading-4xl--line-height': '1.1',
  '--text-heading-4xl--margin-top': '2rem',
  '--text-heading-3xl': '1.875rem',
  '--text-heading-3xl--line-height': '1.15',
  '--text-heading-3xl--margin-top': '1.5rem',
  '--text-heading-2xl': '1.5rem',
  '--text-heading-2xl--line-height': '1.2',
  '--text-heading-2xl--margin-top': '1rem',
  '--text-heading-xl': '1.25rem',
  '--text-heading-xl--line-height': '1.25',
  '--text-heading-xl--margin-top': '1rem',
  '--text-heading-lg': '1.125rem',
  '--text-heading-lg--line-height': '1.35',
  '--text-heading-lg--margin-top': '1rem',
  '--text-heading-md': '1rem',
  '--text-heading-md--line-height': '1.5',
  '--text-heading-md--margin-top': '1rem',
  '--text-heading-sm': '0.875rem',
  '--text-heading-sm--line-height': '1.5',
  '--text-heading-xs': '0.75rem',
  '--text-heading-xs--line-height': '1.5',
  '--text-base-lg': '1rem',
  '--text-base-lg--line-height': '1.5',
  '--text-base-md': '0.9375rem',
  '--text-base-md--line-height': '1.5',
  '--text-base-sm': '0.875rem',
  '--text-base-sm--line-height': '1.5',
  '--text-base-xs': '0.75rem',
  '--text-base-xs--line-height': '1.5',
  '--font-weight-normal': '400',
  '--font-weight-semibold': '600',
  '--font-weight-bold': '700',
  '--radius-md': '8px',
  '--radius-lg': '12px',
  '--site-max-width': '1440px',
  '--site-padding-x': '16px',
});
